name: calval_CSLC
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python=3.11.4
 - pip=23.1.2
 - boto3=1.26.54
 - dateparser>=1.1.4
 - dask>=2022.12.1
 - dask-jobqueue=0.8.2
 - folium=0.14.0
 - fsspec=2023.5.0
 - geopandas=0.13.2
 - h5py=3.9.0
 - ipympl=0.9.3
 - isce3=0.13.0
 - lxml=4.9.2
 - matplotlib=3.7.1
 - mintpy=1.5.1
 - netcdf4=1.6.4
 - numpy=1.25.0
 - pandas=2.0.3
 - pymap3d=3.0.1
 - pysolid=0.3.0
 - pyproj=3.6.0
 - rasterio=1.3.7
 - requests=2.28.1
 - ruamel.yaml=0.17.32
 - scipy=1.11.1
 - s3fs=2023.5.0
 - yamale=4.0.4
 # for testing and distribution
 - flake8=6.0.0
 - flake8-import-order=0.18.2
 - flake8-blind-except=0.2.1
 - flake8-builtins=2.1.0
 - ipykernel=6.19.4
 - jsonschema=3.2.0
 - jupyter=1.0.0
 - packaging=22.0
 - papermill=2.3.4
 - pytest=7.2.0
 - pytest-cov=4.0.0
 - setuptools=65.6.3
 - setuptools_scm=7.1.0
