name: calval-CSLC_dev
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python>=3.9
 - pip
 - dateparser
 - dask>=1.0
 - dask-jobqueue>=0.3
 - folium
 - geopandas
 - gdal>=3
 - ipympl
 - isce3
 - lxml
 - matplotlib
 - mintpy
 - netcdf4
 - numpy
 - pandas
 - pysolid
 - pyproj
 - rasterio
 - requests
 - ruamel.yaml
 - scipy
 - yamale
 # for testing and distribution
 - flake8
 - flake8-import-order
 - flake8-blind-except
 - flake8-builtins
 - ipykernel
 - jsonschema==3.2.0
 - jupyter
 - packaging
 - papermill
 - pytest
 - pytest-cov
 - seaborn
 - setuptools
 - setuptools_scm
 - pip:
   - pdfkit
